import '@/styles/_main.scss'

import {custom_fonts} from './fonts'
// component 
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${custom_fonts}`}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  ) 
}
