export const articles = [
  {
    id: 1,
    img: "article1",
    title: "Can a New U.N.Envoy Produce Peace in Yemen?",
    date: "26 Feb 2023",
    recource_name: "Middle East Institute",
    recource_icon: "recource1",
  },
  {
    id: 2,
    img: "article2",
    title: "Yemen’s Prisoner Exchange must be depolarized",
    date: "26 Feb 2023",
    recource_name: "Sanaa Center for Strategic Studies",
    recource_icon: "recource2",
  },
  {
    id: 3,
    img: "article3",
    title: "The Houthis’ End Game in Yemen, Al-Jazeera",
    date: "26 Feb 2023",
    recource_name: "Al-Jazeera English",
    recource_icon: "recource3",
  },
  {
    id: 4,
    img: "article1",
    title: "The Biden Administration needs a Yemen policy",
    date: "26 Feb 2023",
    recource_name: "Middle East Institute",
    recource_icon: "recource1",
  },
  {
    id: 5,
    img: "article2",
    title: "Yemen’s Prisoner Exchange must be depolarized",
    date: "26 Feb 2023",
    recource_name: "Sanaa Center for Strategic Studies",
    recource_icon: "recource2",
  },
  {
    id: 6,
    img: "article3",
    title: "The Houthis’ End Game in Yemen, Al-Jazeera",
    date: "26 Feb 2023",
    recource_name: "Al-Jazeera English",
    recource_icon: "recource3",
  },
];

export const stories = [
  {
    id: 1,
    img: "article1",
    title: "The Biden Administration needs a Yemen policy",
    date: "26 Feb 2023",
    recource_name: "Middle East Institute",
    recource_icon: "recource1",
  },
  {
    id: 2,
    img: "article2",
    title: "Yemen’s Prisoner Exchange must be depolarized",
    date: "26 Feb 2023",
    recource_name: "Sanaa Center for Strategic Studies",
    recource_icon: "recource2",
  },
  {
    id: 3,
    img: "article3",
    title: "The Houthis’ End Game in Yemen, Al-Jazeera",
    date: "26 Feb 2023",
    recource_name: "Al-Jazeera English",
    recource_icon: "recource3",
  },
  {
    id: 4,
    img: "article1",
    title: "The Biden Administration needs a Yemen policy",
    date: "26 Feb 2023",
    recource_name: "Middle East Institute",
    recource_icon: "recource1",
  },
  {
    id: 5,
    img: "article2",
    title: "Yemen’s Prisoner Exchange must be depolarized",
    date: "26 Feb 2023",
    recource_name: "Sanaa Center for Strategic Studies",
    recource_icon: "recource2",
  },
  {
    id: 6,
    img: "article3",
    title: "The Houthis’ End Game in Yemen, Al-Jazeera",
    date: "26 Feb 2023",
    recource_name: "Al-Jazeera English",
    recource_icon: "recource3",
  },
];

export const interviews = [
  {
    id: 1,
    img: "interview",
    title: "Can a New U.N.Envoy Produce Peace in Yemen?",
  },
  {
    id: 2,
    img: "interview-2",
    title: "Can a New U.N.Envoy Produce Peace in Yemen?",
  },
  {
    id: 3,
    img: "interview",
    title: "Can a New U.N.Envoy Produce Peace in Yemen?",
  },
  {
    id: 7,
    img: "interview-2",
    title: "Can a New U.N.Envoy Produce Peace in Yemen?",
  },
  {
    id: 4,
    img: "interview",
    title: "Can a New U.N.Envoy Produce Peace in Yemen?",
  },
  {
    id: 5,
    img: "interview-2",
    title: "Can a New U.N.Envoy Produce Peace in Yemen?",
  },
  {
    id: 6,
    img: "interview",
    title: "Can a New U.N.Envoy Produce Peace in Yemen?",
  },
];

export const reports = [
  {
    id: 1,
    img: "article1",
    title: "The Biden Administration needs a Yemen policy",
    date: "26 Feb 2023",
    recource_name: "Middle East Institute",
    recource_icon: "recource1",
  },
  {
    id: 2,
    img: "article2",
    title: "Yemen’s Prisoner Exchange must be depolarized",
    date: "26 Feb 2023",
    recource_name: "Sanaa Center for Strategic Studies",
    recource_icon: "recource2",
  },
  {
    id: 3,
    img: "article3",
    title: "The Houthis’ End Game in Yemen, Al-Jazeera",
    date: "26 Feb 2023",
    recource_name: "Al-Jazeera English",
    recource_icon: "recource3",
  },
  {
    id: 4,
    img: "article1",
    title: "The Biden Administration needs a Yemen policy",
    date: "26 Feb 2023",
    recource_name: "Middle East Institute",
    recource_icon: "recource1",
  },
  {
    id: 5,
    img: "article2",
    title: "Yemen’s Prisoner Exchange must be depolarized",
    date: "26 Feb 2023",
    recource_name: "Sanaa Center for Strategic Studies",
    recource_icon: "recource2",
  },
  {
    id: 6,
    img: "article3",
    title: "The Houthis’ End Game in Yemen, Al-Jazeera",
    date: "26 Feb 2023",
    recource_name: "Al-Jazeera English",
    recource_icon: "recource3",
  },
];

export const policyPapers = [
  {
    id: 3,
    img: "article3",
    title: "The Houthis’ End Game in Yemen, Al-Jazeera",
    date: "26 Feb 2023",
    recource_name: "Al-Jazeera English",
    recource_icon: "recource3",
  },
  {
    id: 1,
    img: "article1",
    title: "Time to Rethink International Intervention in Yemen",
    date: "26 Feb 2023",
    recource_name: "Middle East Institute",
    recource_icon: "recource1",
  },
  {
    id: 2,
    img: "article2",
    title: "Yemen’s Prisoner Exchange must be depolarized",
    date: "26 Feb 2023",
    recource_name: "Sanaa Center for Strategic Studies",
    recource_icon: "recource2",
  },

  {
    id: 4,
    img: "article1",
    title: "The Biden Administration needs a Yemen policy",
    date: "26 Feb 2023",
    recource_name: "Middle East Institute",
    recource_icon: "recource1",
  },
  {
    id: 5,
    img: "article2",
    title: "Yemen’s Prisoner Exchange must be depolarized",
    date: "26 Feb 2023",
    recource_name: "Sanaa Center for Strategic Studies",
    recource_icon: "recource2",
  },
  {
    id: 6,
    img: "article3",
    title: "The Houthis’ End Game in Yemen, Al-Jazeera",
    date: "26 Feb 2023",
    recource_name: "Al-Jazeera English",
    recource_icon: "recource3",
  },
];

export const unpublishedResearches = [
  {
    id: 3,
    title: "The Houthis’ End Game in Yemen, Al-Jazeera",
    date: "26 Feb 2023",
    recource_name: "Al-Jazeera English",
    recource_icon: "recource3",
  },
  {
    id: 1,
    title: "Time to Rethink International Intervention in Yemen",
    date: "26 Feb 2023",
    recource_name: "Middle East Institute",
    recource_icon: "recource1",
  },
  {
    id: 2,
    title: "Yemen’s Prisoner Exchange must be depolarized",
    date: "26 Feb 2023",
    recource_name: "Sanaa Center for Strategic Studies",
    recource_icon: "recource2",
  },

  {
    id: 4,
    title: "The Biden Administration needs a Yemen policy",
    date: "26 Feb 2023",
    recource_name: "Middle East Institute",
    recource_icon: "recource1",
  },
  {
    id: 5,
    title: "Yemen’s Prisoner Exchange must be depolarized",
    date: "26 Feb 2023",
    recource_name: "Sanaa Center for Strategic Studies",
    recource_icon: "recource2",
  },
  {
    id: 6,
    title: "The Houthis’ End Game in Yemen, Al-Jazeera",
    date: "26 Feb 2023",
    recource_name: "Al-Jazeera English",
    recource_icon: "recource3",
  },
];
